before_script:
    - composer self-update
    - composer install --prefer-dist --no-interaction --dev  > /dev/null
    - export APP_ENV=local
    - php artisan key:generate
    - php artisan migrate --force
    - php artisan db:seed --force
    - php artisan jwt:generate

unitTesting:
    script:
        - php vendor/bin/phpunit --colors --debug